# Generated by Django 4.1.5 on 2023-03-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='product',
        ),
    ]
