# Generated by Django 4.1.5 on 2023-03-10 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_rename_project_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='blog/')),
                ('postby', models.CharField(default='Admin', max_length=50)),
                ('poston', models.DateField(default=datetime.date(2023, 3, 10))),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
