# Generated by Django 4.1.5 on 2023-03-22 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_lab_alter_blog_poston'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Type', models.TextField()),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='Testing/')),
            ],
            options={
                'db_table': 'Testing',
            },
        ),
        migrations.RemoveField(
            model_name='lab',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='photo',
        ),
        migrations.AddField(
            model_name='lab',
            name='Address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lab',
            name='Location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 3, 22)),
        ),
    ]
