# Generated by Django 4.1.5 on 2023-03-28 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_testing_remove_lab_description_remove_lab_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='photo',
        ),
        migrations.AddField(
            model_name='lab',
            name='photo',
            field=models.ImageField(default='', upload_to='lab/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 3, 28)),
        ),
    ]
