# Generated by Django 4.1.5 on 2023-03-31 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_remove_testing_photo_lab_photo_alter_blog_poston'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='photo',
            field=models.ImageField(default='', upload_to='Testing/'),
        ),
        migrations.AddField(
            model_name='testing',
            name='sample',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 3, 31)),
        ),
    ]
