# Generated by Django 4.1.5 on 2023-04-04 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_testing_photo_testing_sample_alter_blog_poston'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testing',
            old_name='sample',
            new_name='FastingRequirement',
        ),
        migrations.AddField(
            model_name='testing',
            name='TubeType',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='testing',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testing',
            name='sampleType',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 4, 4)),
        ),
        migrations.AlterField(
            model_name='testing',
            name='Type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='testing',
            name='price',
            field=models.IntegerField(max_length=100),
        ),
    ]
