# Generated by Django 4.1.5 on 2023-04-06 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_rename_sample_testing_fastingrequirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 4, 6)),
        ),
    ]
