# Generated by Django 4.1.5 on 2023-04-07 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_alter_blog_poston'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 4, 7)),
        ),
        migrations.AlterField(
            model_name='lab',
            name='Location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
