# Generated by Django 4.1.5 on 2023-04-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_alter_blog_poston_alter_lab_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='Location',
            field=models.TextField(default=''),
        ),
    ]
