# Generated by Django 4.1.5 on 2023-04-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_alter_lab_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='Type',
            field=models.TextField(default='', max_length=100),
        ),
    ]
