# Generated by Django 4.1.5 on 2023-04-08 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_alter_testing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 4, 8)),
        ),
        migrations.AlterField(
            model_name='testing',
            name='Type',
            field=models.TextField(default='', max_length=900),
        ),
        migrations.AlterField(
            model_name='testing',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
