# Generated by Django 4.1.5 on 2023-04-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_rename_type_testing_packageincludes_testing_reports_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testing',
            old_name='packageincludes',
            new_name='Type',
        ),
    ]
