# Generated by Django 4.1.5 on 2023-04-20 03:48

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0019_rename_packageincludes_testing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 4, 20)),
        ),
        migrations.AlterField(
            model_name='testing',
            name='Type',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='testing',
            name='description',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
