# Generated by Django 4.1.5 on 2023-04-20 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0020_alter_blog_poston_alter_testing_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testing',
            old_name='Type',
            new_name='PackageIncludes',
        ),
    ]
