# Generated by Django 4.1.5 on 2023-04-27 05:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0021_rename_type_testing_packageincludes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 4, 27)),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('PhoneNo', models.CharField(max_length=20)),
                ('Appointmentdate', models.CharField(max_length=20)),
                ('Appointmenttime', models.CharField(max_length=20)),
                ('Bookingdate', models.CharField(max_length=20)),
                ('Labid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
                ('Testid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.testing')),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
    ]
