# Generated by Django 4.1.5 on 2023-05-01 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0022_alter_blog_poston_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 5, 1)),
        ),
    ]
