# Generated by Django 4.1.5 on 2023-05-19 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0025_subcribe_alter_blog_poston'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 5, 19)),
        ),
        migrations.AlterField(
            model_name='patientreports',
            name='PatientFeedback',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
